### ISSUE TITLE
Modifying partition table format

### ISSUE THREAD

**Issue by Treebro** [maxnet/berryboot#101]
Wanting to modify how large the mmcblk0p1 is partitioned through berryboot gui.
I found these lines of code that are responsible I believe:

   if (_reformatBoot)
partitionTable = "2048,129024,0E\n"; /\* 63 MB FAT partition LBA _/
// partitionTable = "0,128,6\n"; /_ 64 MB FAT partition _/
partitionTable += "131072,,L\n"; /_ Linux partition with all remaining space */
partitionTable += "0,0\n";
partitionTable += "0,0\n";
if (!_reformatBoot)
partitionTable += "0,0\n";

It looks like I would need to change:
 partitionTable = "2048,129024,0E\n"; /\* 63 MB FAT partition LBA */
But I'm not familiar with this syntax...  And I don't know what I would search google for in this situation...
Is there a simple rule to follow or would you be able to link me to some resources to read?

**Comment by maxnet** [comment]
Numbers are in sectors (512 bytes)
2048,129024,0E = let partition start at 1 MB, size 63 MB, partition type 0xE (FAT16 LBA addressing)

**Comment by Treebro** [comment]
Found out it is just passing that string to sfdisk in the next block of commands... I didn't notice that right away.    Would modifying these values break other parts of the program?  I notice there is open space between the end of partition 1 and start of partition 2.

**Comment by maxnet** [comment]
Second number is size, not end sector.
Sorry for the confusion.
There is no spare space between partitions, just at the beginning of the disk (for alignment, and because an u-boot blob is written there on some platforms like Allwinner)

> Would modifying these values break other parts of the program?

Nope.
You might also want to modify this value though if you intend to ship more than 63 MB of files: https://github.com/maxnet/berryboot/blob/berryboot2.0/BerrybootGUI2.0/driveformatthread.cpp#L63
Also remember that all files are copied to memory temporarily, so must fit in the memory of the device you plan to use.

**Comment by Treebro** [comment]
This is working wonderfully so far.  Thank you very much for the help!
