### ISSUE TITLE
Update Openelec on BerryBoot (rasp pi 1)

### ISSUE THREAD

**Issue by Haris1977** [maxnet/berryboot#151]
Greetings.

As there are newer versions of Openelec than the one in bb, i m trying to update openelec bb image. I tried 2 different situations:

1) Put the *.tar image into .update folder. This works for standard OE but not in bb
2) Replaced Openelec.img with SYSTEM image (of the tar file) in /var/media/berryboot/images/ folder. It works but it doesnt update. I just have to redo all my settings again !!!

Am i missing smth here?

p.s: i ve downloaded the OpenELEC-RPi.arm.5.0.6.tar file and not the img file..

**Comment by Maxximo88** [comment]
I'm interested too, same problem on Raspberry Pi2!

**Comment by Haris1977** [comment]
Any news about that?

**Comment by sM0Ke** [comment]
Same here

**Comment by g1t-dlanor** [comment]
I'm not sure how/if you can update an existing OpenELEC OS running through BerryBoot, but it's very simple to make a fresh install for BerryBoot of any OpenELEC release for RPi, by using one of the files included in each such release intended for standalone use on a separate SD card. The same method also applies to all releases of the RasPlex project, since that too is based on OpenELEC and uses the same methods.

You only need the "SYSTEM" file installed with others on each SD card for standalone OpenELEC.
So if you install OpenELEC as for standalone use on an SD card or USB drive (doesn't matter which), you can then copy just the "SYSTEM" file to a PC and rename it to some suitable name such as "BB2_OpenELEC-RPi2.arm-5.0.8.img". Most of the name is arbitrary, except for the extension which should be ".img". And personally I prefer to add a "BB1" or "BB2" prefix to this kind of image filename to indicate that it is a BerryBoot compatible squashfs image and whether it's suitable for an RPi1 or RPi2 model.

Another way of getting the same file is to download the TAR file with part-compiled source code for the OpenELEC project, which should include the "SYSTEM" file in the same form as used on installed SD cards. You can simply copy that "SYSTEM" file from inside the TAR file to your PC, and rename it as mentioned above.

Once you have such an image file you can place it on a FAT32-formatted USB stick and insert this into the RPi and then use BerryBoot's menu command "Copy OS from USB stick" (in the drop-down menu that appears if you long-click the "Add OS" entry in the main menu). This will install the new OpenELEC version exactly as when you installed the new one (which loaded a similar SYSTEM file over Internet).

Like the first time this will be a brand new installation, so you will have to configure everthing from scratch again, including the choice of XBMC/Kodi skins and other add-ons to use.

**Comment by smileybob** [comment]
The first thing to remember when using berryboot is that it uses the squashfs images to load the OS. the image never gets written to and so therefore any changes are recorded seperately.
With this in mind what you need to achieve is to simply replace the OS squash image with a newer version whilst keeping its original name you have given to it and thus still leaving the saved changed files working from the new image.

Haris1977, you are on the right track, you cannot be loaded into the image you are trying to update, so you have to create a temporary clone to load into to then update the original, here are the instructions:

So with openelec in mind, I do the following to update the OS:

On a windows pc Download a program called winscp. https://winscp.net/eng/download.php. choose either the installation package or the Portable, its up to you.

goto openelec website http://openelec.tv/get-openelec and download the openelec not maked as the disk image, (when you select it the file will end with tar).

open the downloaded file using winrar or another similar compression tool and extract the file named "system" (this is the squashfs openelec file!) from the target directory (remember the location you extract this).

On the raspberry Pi load into the berryboot os selection screen, select "edit menu", then select your Openelec image and click on clone image, select to copy the changed data and give it a relevant name such as "test" or "cloned openelec".

Next reboot and select the new Openelec you just created and then load.

Now goto your PC and load winscp and connect to openelec usind the IP address its been given on your network along with the username (root) and password (openelec).

Winscp will load a split directory list, the left side is your pc, the right is your raspberry pi.

At the top of winscp, select options-preferences then select panels, make sure that "show hidden files" is ticked. then click ok.

In the right panel (your openelec instance) click on the .. to go up a level and then you should be now located in the <root> directory.

Next go into var-media-berryboot-images. This is where your image files are loaded in berryboot
.
Still in the right panel you need to then change the name of your original openelec image file by adding .bak to it (this is the one you`ve been using and want to update).

on the left screen locate the system file you extracted earlier. drag this file over to the right panel and then select copy, next rename this file to the original openelec file but without the bak, this has now replaced the old openelc with the new one which will be loaded when you reboot and keep all of your original setting!!!

I will try this method soon with retropie

This looks long winded but once you understand what you have just done, you will be able to do this with ease next time :)

I Hope this helps, any problems let me know :)

**Comment by maxnet** [comment]
> 2) Replaced Openelec.img with SYSTEM image (of the tar file) in /var/media/berryboot/images/ folder.

That should be sufficient.

> It works but it doesnt update. I just have to redo all my settings again !!!

If it doesn't work, then the OS probably changed the format they store the settings in.
Would argue that detecting the older configuration format on startup, and running any update scripts should be the OS's responsibility, rather than Berryboot's.

**Comment by smileybob** [comment]
I've been doing my method for quite some time now, I've never had to redo my settings!
 I've tried making changes to the image whilst I've been loaded into it and it doesn't work, just like you've found out!!
Give my method a try before dismissing it ;)

**Comment by g1t-dlanor** [comment]
@smileybob:
I found your post very interesting, not so much because of its direct application for OpenELEC, but mainly because it implies the ability of an installed OS with FTP/SCP features to be used for maintenance, backup and updating of other installed OS instances. That could prove very useful for a lot of different use cases.

**Comment by smileybob** [comment]
Your welcome g1t-dlanor
Im forever dabbling in winscp and putty connecting to the rpi and making changes and copying files, so easy once you know how, I'm still learning loads of stuff and developing what I can do with it, berryboot  is such a good tool, wouldn't be without it now 😊

**Comment by maxnet** [comment]
> I've tried making changes to the image whilst I've been loaded into it and it doesn't work, just like you've found out!!

Might not work if you are running that distro right now.
But should work if you boot another distro. E.g. start Raspbian, update OpenELEC from there.
At least when configuration files are compatible between versions.

**Comment by smileybob** [comment]
that's right, or if you haven`t got another OS image installed in berryboot, then you can just boot into a clone of the Openelec image your updating as I have described above.

**Comment by Haris1977** [comment]
Guys thanks for your advices..Smileybob thank you but as you can understand this is too cumbersome for the bb's users. This is my thought for updating the image in 3 steps (but I AM NOT SURE IF this can be happen. I don't have berryboot right know, but if someone can try it, this would be very helpfull for everyone in here!!)

Step 1: Take a backup of your existing openelec image by going in Programm addons=>Openelec=>System=>Back up=>Create system and kodi back up

Step 2: Follow my instructions (Replace Openelec.img with the new and updated SYSTEM image (of the tar file) in /var/media/berryboot/images/ folder)

Step 3: You are going to have the updated image now, but you have to redo all your settings. In order to avoid it go into Programm addons=>Openelec=>System=>Back up=>Restore backup.

I guess this will work. Please someone try it and tell here about the results!! What "we" expect to restore is:

-Skins
-Add-ons (video/music/image)
-Favorites e.t.c

But..i keep my fingers crossed..

**Comment by smileybob** [comment]
Hi Harris,
It's not that complicated, it looks complicated because I have given step by step instructions.
The short version would be:

1.clone your openelec within berryboot.

2.boot into the cloned openelec.

3.download the new openelec system file.

4.replace the system.img in your original openelec.
Done, that's the basics and it takes 5 mins to do and you don't need to redo your settings.
Just try my guide, it's quite sime really.

**Comment by Haris1977** [comment]
Can anyone try my steps too? I am crossing my fingers though..

Thanks smileybob!

**Comment by iamgreenbag** [comment]
I just went through this tonight with LibreELEC. If you need to back up your settings, tweaks and addons, then you should save what's in the ~/berryboot/data/OpenELEC-7.0.2.img folder.. specifically the /usr and /storage directories. If you install a new version of OpenELEC or LibreELEC, then you just need to copy those directories back. .. I haven't done it myself yet, but I've read that's how to back up your settings with a normal OpenELEC install. Updating was pretty easy.. I have Raspbian as the first os, so I did everything from the Pi. Downloaded the tar, extracted, copied and replaced.. then rebooted. That easy. :)
