### ISSUE TITLE
Cannot Add ROM's to RetroPie

### ISSUE THREAD

**Issue by BananaBoie** [maxnet/berryboot#162]
Can you make a way to add ROM's to RetroPie (like Drag and Drop) or if you have a way to do it. I'm Fairly new to this.

**Comment by BananaBoie** [comment]
BTW I got retropie with berryboot

**Comment by LucidEye** [comment]
You need to first download and install the RetroPie image from the berryboot available OS menu.
(Use at least a 32gb class 10 SD card if you plan on installing a lot of games and/or are running multiple OSes or you may run out of room real fast!)
Then select and boot into RetroPie... 
When you first boot into the RetroPie OS it will automagically create the ~/berryboot/data/RetroPie_2.3.img/ directory.
In that directory will be the /home/pi/ directory... (BUT IT WILL BE EMPTY)
Now shutdown your Pi and put the berryboot card into your laptop or desktop and...
FROM A SEPARATE WORKING INSTALL of RetroPie on another SD card, you will need to copy the /home/pi/RetroPie/ and /home/pi/RetroPi-Setup/ directories into the ~/berryboot/data/RetroPie_2.3.img/home/pi directory.
Now you can add your game ROMs and BIOS files there.
Once you've copied or added all your ROMs, put the berryboot card back in your Pi and boot to the RetroPie OS and you should be able to see and play your ROMs... don't forget to do all the controller and other configurations first.

It would be REALLY NICE if the folks at berryboot would offer a wiki or something with these important setup details for people who aren't so Linux savvy!

**Comment by LucidEye** [comment]
Also, make sure to edit your /etc/wpa_supplicant/wpa_supplicant.conf file so that RetroPie will connect to your WiFi... then boot into RetroPie and EXIT from the Emulation Station to get to a CLI prompt.
Then run sudo apt-get update, let that finish...
Then run sudo apt-get upgrade, let that finish and REBOOT!
Boot back into berryboot, boot RetroPie, exit Emulation Station to get to a CLI prompt again.
Type cd RetroPie-Setup to enter that directory...
run sudo ./retropie_setup.sh then select Update RetroPie-Setup Script (THIS IS VERY IMPORTANT TO DO FIRST! or the script will not update RetroPie to the latest version)
Once the update script finishes updating exit the script and then run it again sudo ./retropie_setup.sh ... then select the UPDATE BINARIES from the menu... this will update Emulation Station and all your emulators to bring you up to the latest full version of RetroPie.  Be prepared for this step to take a while... even hours.
The RetroPie version offered in the berryboot available OS download menu is OUTDATED (RetroPie Ver 2.3)  As of writing this the latest stable version is 2.6 (and 3.0 BETA is also available).  The latest version has MUCH better GUI configuration support for controllers and other things!

**Comment by ccsliinc** [comment]
I followed these instruction and now i receive a notice stating "it looks like your systems configuration file has not been set up or is invalid. You'll need to do this by had unfortunately.

**Comment by LucidEye** [comment]
Oops, yeah... you also need to copy the ~/home/pi/RetroPie-Setup directory from the SEPARATE working copy of Retro Pie to the berryboot SD card.
Yeah, like I said, the developers at berryboot NEED to do this kind of setup work and provide their users with proper directions on how to perform setups and upgrades since berryboot changes how a distro sets up it's partitions and directory structure!

**Comment by maxnet** [comment]
Closing as Retro Pie version has been updated.
