### ISSUE TITLE
iSCSI reboot

### ISSUE THREAD

**Issue by Htaborda** [maxnet/berryboot#167]
I manage to install Berryboot on a RPi2, with a iSCSI target (a ReadyNAS OS6).
No issues, everything works fine.

However, everytime (and in every OS) I order the system to reboot, it hangs.
Why?

**Comment by peter0123** [comment]
hi, i work only with iscsi on different nas systems.
i have no problem with Pi + Pi2.
I think you need only a firmware upgrade on your nas, or the problem is your nas.
Test it on your computer, make a iscsi drive, copy the files from the nas and use this for one test.. (edit your scsi file on the sd)

**Comment by lgb-this** [comment]
I use a QNAP TS-451 together with a RPI2 and i have the same problems with the reboot. The PI does not find the iSCSI server after the reboot. I have to power off and on the PI to boot successfully.

**Comment by Ikyrz** [comment]
i've the problem with a pi 2 and a synology nas
berryboot last version, an idea ?
thanks
