### ISSUE TITLE
mksquashfs error

### ISSUE THREAD

**Issue by chrome511** [maxnet/berryboot#169]
with berryboot for pi2 i cant backup my system (image + data)
i get the following error:

mksquashfs error

error creating image.

FATAL ERROR: mksquashfs requires more physical memory than is available!

this is the berryboot which i have loaded: http://downloads.sourceforge.net/project/berryboot/berryboot-20150401-pi2-only.zip

with a normal image without any modification the backup works.
used OS is raspian wheezy

**Comment by g1t-dlanor** [comment]
I have exactly the same problem, though I tried it with other OS. (OS choice is irrelevant here.)

The RPi2 has 1GB of RAM, which is more than any other RPi model possesses.
So if mksquashfs really needs more RAM, then backup of modified images is impossible in ALL models.

Personally I suspect some bug in how free RAM is checked/requested.
Either that or a hideous bug in some buffer allocation size used for mksquashfs in these cases.
Either way, it needs to be fixed if BerryBoot is to be used seriously.
(I.E. Serious usage without backup ability for modifications is not an option...)

The bug has been present in at least two public releases, since I use an earlier release of BerryBoot v2.0 which I downloaded as "berryboot-20150211-pi2-only.zip".

I discovered the problem in trying to make the backups needed to migrate my current OS collection for use with the newest BerryBoot release. Last time I killed the entire collection by just upgrading the SD card files, which then had no way of adopting the old OS collection, so I lost everything and had to reinstall and reconfigure all OS and their app/data files from scratch. If I have to do the same again, then I have no choice but to abandon BerryBoot for good. Without proper backup ability for the current state of each OS the entire BerryBoot system is pointless.
NB: This problem is also discussed in issues #149 and #183.

**Comment by maxnet** [comment]
Probably related to: https://github.com/plougher/squashfs-tools/commit/5282a3c0570a62b53157143aafb59418ae9bf257

Should include a more recent version of squashfs-tools in Berryboot in the next release, but have little time at the moment.

**Comment by g1t-dlanor** [comment]
I agree that changes to that code section could solve this problem, though several suspect items in it remain unclear in this short listing, such as the SQUASHFS_LOWMEM value, which in itself could cause this problem. But the code visible here also shows other worrisome assumptions by its coder, such as the check for mem divided by SQUASH_TAKE being larger than 640MB, which to my mind implies that the squashfs coder expected to have access to multiple buffers of 640MB size, which is impossible on any RPi unit (assuming myself that SQUASH_TAKE > 1, and that all mem values are scaled like phys_mem in the early part of the listing).
This reminds me of a bug we ran into recently in the RasPlex project where ASS subtitles gave problems, because a recent version of libass assumed it could use two work buffers of 512MB each... Many coders today are just 'spoiled' by modern computers with lots of RAM, causing them to lose the ability (or at least the tendency) to code well for low-end systems.

**Comment by maxnet** [comment]
> But the code visible here also shows other worrisome assumptions by its coder, such as the check for 
> mem divided by SQUASH_TAKE being larger than 640MB, which to my mind implies that the squashfs 
> coder expected to have access to multiple buffers of 640MB size

Quite to the contrary.
When compiled for a 32-bit system, the author LIMITS the buffer to 640 MB.

``` c
    if(sizeof(void *) == 4 && mem > 640) {
        /*
         * If we're running on a kernel with PAE or on a 64-bit kernel,
         * the default memory usage can exceed the addressable
         * memory by this process.
         * Due to the typical kernel/user-space split (1GB/3GB, or
         * 2GB/2GB), we have to conservatively assume the 32-bit
         * processes can only address 2-3GB.  So limit the  default
         * usage to 640M, which gives room for other data.
         */
        mem = 640;
    }
```

**Comment by g1t-dlanor** [comment]
Ah, I see. That is of course better. I missed that since the code segment showing that limitation was not visible in the previously linked source page without expanding at the diff limits, which I didn't do then. But the comments in that expanded section clearly show that the original coder is assuming a normal PC with several GB of RAM available, and that he limits the buffer usage mainly to suit the limited address range of 32-bit processes. On such a computer this limitation would leave plenty of RAM for other uses, but 640MB dedicated to squashfs buffers is still a bit much even on an RPi2, since your X-windows libs and other stuff needed by the BerryBoot menu and its subfunctions  must also need some memory. And on an RPi1 the attempt to use 640MB will of course fail regardless of other memory usage.

Most likely mksquashfs would work equally well with all (or most) of its RAM buffers much lower than the original minimums, and hopefully those diffs will accomplish that, so that all RPi models can use mksquashfs for backups in future BerryBoot versions.

But that still leaves the question open as to how we can migrate our existing installations made with current BerryBoot to such a new version on new media, without losing all changes made since installing those OS images. It should be possible to code a backup utility for use in Linux on a PC, to perform a backup of existing BerryBoot media, producing backup files identical to those needed by BerryBoot for restoration on new media. (And even Windows users could do such backup using VMware or VirtualBox.)

**Comment by maxnet** [comment]
> And on an RPi1 the attempt to use 640MB will of course fail regardless of other memory usage.

It will not use 640 MB if there is less...
Only limit the amount detected to 640 MB if there is more.

Actually, I do think it may be using more memory on the Pi 2 for other reasons, it can run tasks in parallel on multi-core systems.
Did anyone receive this error when backing up a Pi 1?

If the problem only occurs on the Pi 2 due to that, telling mksquashfs to use only one core by adding:
 `<< "-processors" << "1"` to the argument list at https://github.com/maxnet/berryboot/blob/2cef90d90157e729b7b195cf4e4f581840567e48/BerrybootGUI2.0/mainwindow.cpp#L476 may improve things.
Don't have time to test that right now though.

**Comment by MOhlmann** [comment]
I have testet with this opions

<< "-processors" << "1"

It not works. 

FATAL ERROR: mksquashfs requires more physical memory than is available!

**Comment by g1t-dlanor** [comment]
I doubt that it will be possible to get around this problem using our existing BerryBoot setups.
Most likely it will require a new BerryBoot build with modified lib for mksquashfs to do this.
