### ISSUE TITLE
TOTALLY WRECKED 16GB MICRO SD CARD ON RASPBERRY PI2

### ISSUE THREAD

**Issue by ianmhopton** [maxnet/berryboot#174]
GREAT PROGRAME, (SARCASM) AFTER MULYIPLE ATTEMPTS TO DOWNLOAD RASPIAN,  EVENTUALLY GOT RASPIAN. SO FAR SO GOOD.
 LOOKED FOR KALI IN "OTHER" WASNT THERE. SHUT DOWN RPI 2.
DECIDED TO WRITE KALI IMAGE USING WINDOWS 7. ( PEAZIP & DISK IMAGER,)
PUT SD MICRO 16GB IN CARD READER....ONLY SHOWED UP AS 60MB..
TOTALLY FUCKED MY SD CARD. 
THANKS A FUCKING BUNCH.

**Comment by smileybob** [comment]
Please do not swear or have a go at someone who has written a program FOR FREE for everyone to benefit from.
Now this forum is for people to ask questions so that others can try to help you if needed.
I would imagine your question would be something like this:
Hi, after using berry boot my ad card now only shows as 64mb in size, please could you help?
My reply to you would then be something like:
Hi, could you try looking for a program called sd formatter, download this on your windows 7 machine and use the program to select the drive and then format it. The SD card should now be the correct size again.
Any problems let me know 😉

Berryboot is a great program and the producer does it because he can and wants others to benefit from his or her hard work. Comments like yours can really upset people, what's the point?

**Comment by ianmhopton** [comment]
Sorry, I had had a really bad day and you are totally correct. Thank you
for making the effort to provide program. And thank you for the advice re
reformatting sd card, tried doing that with Windows, didn't work. Hopefully
recover? Please accept my sincere apology.

**Comment by maxnet** [comment]
> And thank you for the advice re reformatting sd card, tried doing that with Windows, didn't work

Using which formatting program?

SD formatter like bob suggested?
https://www.sdcard.org/downloads/formatter_4/

**Comment by ianmhopton** [comment]
Sorry, my bad English!

Had tried reformatting card using Windows....no luck.

Used SD Formatter like Bob suggested, didn't think it would work because it
only saw 64gb when I opened SD Formatter, however closed and tried again
and it totally recovered SD card to 16gb.

Thanks and apologies to Bob again.
