### ISSUE TITLE
BB uses outdated boot files?

### ISSUE THREAD

**Issue by Rad77** [maxnet/berryboot#18]
I had an issue with one of my two Pi's where it would boot from a Raspbian image but could not boot BB (just brief flash of green ACT led).   This was with BB 20130225 and also a slightly earlier version that I tried originally.

I was able to fix the issue by updating the RasPi boot files on the BerryBoot installation using the current files at https://github.com/raspberrypi/firmware/tree/master/boot and can now boot into BB as normal.  This also worked for another user who tried it after experiencing the same issue.

**Comment by maxnet** [comment]
Thanks for the bug report.

The Berryboot build script pulls the firmware from the "next" branch.
Which no longer seems to be updated: https://github.com/raspberrypi/firmware/commits/next

I see there is a new commit labeled "Add support for Hynix 512M and Nanya 256M and 512M SDRAMs" on the "master" branch:  https://github.com/raspberrypi/firmware/commit/ce9dbf9cd8a5d9346b563dbcbfe1ea79f72cc912
Always nice when vendors silently replace parts, without informing their customers other than a line like that hidden on github... _sigh_

Am I correct in assuming your "problem Pi" has a Hynix or Nanya memory chip, instead of the usual Samsung?

**Comment by Rad77** [comment]
Yep, looks like that's the one - I just checked and it has a Hynix chip.
PS. Big thanks to everyone working on Berryboot!

**Comment by maxnet** [comment]
Updated the Berryboot .zip file and update files.

I don't have a "problem Pi" to test it on though.
So could you try updating Berryboot through the "add OS" window, and tell me if it still boots after the update?

**Comment by Rad77** [comment]
Great - It looks like that's a wrap!  Here is my test process...

I had a 2nd Hynix Pi delivered today and used that as my testbed.

Test 1 
  Carried out your suggested test on my working hacked image - updated and yes it still boots.

Test 2  
  Installed the original failing Berryboot image onto SD and it failed to boot as expected.  
  Updated this Berryboot, also via "add OS" (running the update process on the older Pi with Samsung memory)
  The updated Berryboot SD now works on both of the Pi's with Hynix memory.

Ideally we now find a tester with a Nanya equipped board. But I guess there's no reason to think that won't work as they said.

**Comment by maxnet** [comment]
Thanks for testing.
Closing as fixed in 20130311 release.

**Comment by Harvs** [comment]
Hi, I have this exact problem and I have a unit with the samsung 252 chip. I tried these three builds and all just gave me one flash of the led and then nothing:  
20130311
20130225
20130213
I've now gone to a dedicated Raspbmc build and it works fine.

**Comment by maxnet** [comment]
There never was any problem with Samsung.
Must be something else.

Make sure you use the safely remove hardware button before removing the sd card when copying over the files on your normal computer.

**Comment by Harvs** [comment]
Well at one point I tried a different bootcode.bin from another forum post. It got one step further and gave me the 3 flashing led saying that the loader.bin was not found. I even tried burning the img berryboot-cubieboard-beta6 instead of just copying the files over. 
That's when I just went for the Raspbmc img to see if it was this build or not. Raspbmc works great.
