### ISSUE TITLE
Problem backing up SD card

### ISSUE THREAD

**Issue by friarbird** [maxnet/berryboot#183]
When attempting to "clone/backup SD card  to external SD card reader" from option on BerryBoot V2.0 Menu Editor the following error message
 comes up;
"Error Capacity too small. Need 14873.5 MB."

The other option is "Image+data  (uncompressed) Export an image that includes all modifications that I have made" 
Error message comes up;
"Mksquashfs 26
Fatal error error creating image
MKsquashfs requires more physical memory than is available".

It seems that each time a clone is made of the SD card a larger capacity is needed. Several brand new 16GB micro SD cards of different brands were used but the same error messages came up for each.

**Comment by g1t-dlanor** [comment]
I believe these two errors are unrelated, though they occur in similar context.
But the Mksquashfs error requiring more memory occurs even when backing up to a normal USB stick, so that error is not tied to SD card usage. That error is discussed separately in issues #149 and #169 .

**Comment by friarbird** [comment]
Thank you for referencing one of the issues, however, the prime issue in my instance  is yet to be addressed so I will restate more clearly.

Cloning a 16GB SDC:
Gives this error: "Error Capacity too small. Need 14873.5 MB."

This issue is due to the fact that SDC's vary in size, even the same type from identical manufacturers vary in the exact number of usable bytes available. Hence it's pot-luck if your target backup SDC happens to be larger than the original, if not the clone will fail with the "Error Capacity too small. ..." error.
Even if the clone succeeds, when later you come to backup the clone an even larger SDC will be needed. Hence as it stands the clone option is not a practical backup system for BerryBoot V2.0. If BerryBoot V2.0 had an option to reduce the target image size by a small amount before it's cloned onto the target SDC the issue would be solved. It would rarely be the case that the source SDC would be completely full so reducing the target size slightly would not be an issue.

**Comment by g1t-dlanor** [comment]
@friarbird:
I agree with you on the problem of varying precise sizes of SD cards. I have run into the same problem myself in other contexts, when trying to backup and restore images using "Win32 Disk Imager". Like you say, such restoration only works if the destination card has storage space at least equal to the original card, regardless of whether or not all available space on the original card was used. This problem applies to all backup methods which simply deal with the card as a binary data block.

But the simple method of just reducing the block size will not work well, even if the eliminated portion was unused, because once the card is in use by system software it must satisfy the filesystem requirements, which will not be the case if any block of sectors near a partition end do not exist.

But a variation of that method can be implemented for the BerryBoot backup feature, in a way that would greatly improve the flexibility of how these backups can be used, not only to restore an OS collection to a similar SD card, but even to migrate them between unrelated media. (as when replacing SD card storage with an external USB HDD)

What needs to be done when making a backup is to scan the OS storage filesystem to determine its 'topmost' used sector, and then create a modified partition table (without modifying the original), wherein that last used sector is also the last available sector for that partition. This allows us to shrink that partition (only in the backup file) to the smallest possible size without losing data. Then the program can create a backup file of the new kind by normal binary dump method including both the FAT partition and the Linux partition just past that last used sector, and using the modified partition table in this file. (NB: This can even be done, by slightly different method, when OS storage is not on the SD card, by combining the FAT block from SD card with the Linux partition from other storage, and adjusting the partition table accordingly.)

Restoration of such a backup would be possible not only to an SD card, but also to other media, which latter should then receive only the Linux partition data of course, which at restoration time can be expanded to fill out the available storage medium, or a user-defined part of it. (On a large HDD the user might want to have other partitions for other purposes too.) Implementing this method might not be as easy as I outlined here. Possibly some of BerryBoot's Linux system files also need adjustment at restoration time, so as to be made properly aware of the new partition size (in case the partition table doesn't suffice), and depending on the filesystem used, any expansion sectors might need to be formatted for proper use as nulled free sectors. But those are details that can be solved.

With such a backup system it would be easy to migrate entire collections of installed OS not only between differently sized SD cards, but also between different types of media, whether based on SD cards, USB drives or networked storage.

Btw: Even if/when such a new backup system is implemented I also consider it important to fix the backup and restoration of individual OS with modifications. But I agree that we can focus on that problem in those other referenced issues.

**Comment by maxnet** [comment]
> This problem applies to all backup methods which simply deal with the card as a binary data block.

Berryboot doesn't treat it as a binary data block, but simply formats the new card, and then copies all individual files on the file system to the new SD card.

Probably just a bug in the code that checks how much space is needed, before that starts.

**Comment by g1t-dlanor** [comment]
If that is the case, then why limit backup to SD cards at all...?

I've currently managed to migrate my existing OS collection from SD card to HDD by using a virtual Ubuntu machine on my Win7 PC, using Linux tools of Ubuntu to pack up the "berryboot" partition of the SD card to a .tar.gz file, which I could then unpack to an ext4 partition I'd prepared on the HDD (which also has other partitions using FAT32 and NTFS). And of course I also patched the cmdline.txt and uEnv.txt files of the new SD card used for booting, so as to point to the correct HDD partition. My RPi2 is currently running well with that setup using any of my installed OS. So my need of an 'internal' backup feature in BerryBoot is no longer as urgent as I felt it to be earlier.

But direct backup from SD to an HDD partition should be possible to do from within the BerryBoot menu as well, and given what you just said it should only require minor code changes. The user needs to have a choice not just of the drive (as in current backup to SD), but also a choice of the partition within the drive (when multiple partitions exist), and formatting that partition should be optional. (Without formatting it's the user's responsibility to ensure that nothing in the new backup conflicts with existing content.)

It's just a suggestion, which you can adopt or discard as you please of course, but I really think such a generic backup feature would be a valuable addition to BerryBoot.

**Comment by maxnet** [comment]
> If that is the case, then why limit backup to SD cards at all...?

You can select a USB stick or drive instead if you want to.
However it will take up the whole drive.

Preserving existing content is problematic, because most people use other file systems like FAT and NTFS.
We really want ext4 for its support for file permissions, symbolic links, etc.

**Comment by g1t-dlanor** [comment]
I was not suggesting preserving content for cases where the users chooses to use an existing FAT or NTFS partition as backup destination. Since ext4 is required such partitions would of course need to be reformatted (with a prompt to the user, so he can choose to abort if he mistakenly chose the wrong partition).

Perhaps I had better clarify what I did mean.
As I see it there are two cases of preserving content which make sense:

Case 1:
It is crucial to preserve content of other partitions than the one the user chooses for OS storage.
And it is also crucial to permit coexistence of such other partitions, as they may be needed to allow convenient copying of data to an HDD by connecting it to a normal PC, which for a Windows system will mean that it lacks native support for ext4, so other filesystem formats are needed. Many of the OS used with the RPi can then use data on such partitions as-is. (eg: both RasPlex and OpenELEC with Kodi can use both FAT32 and NTFS, and any decent Linux should also have such capability)
Another important aspect of this is that users will not be tampering with the OS storage partition when copying data from other systems this way. That partition is effectively protected by the inability of a normal Windows PC to access it (without very special drivers or Linux emulation that is).

Case 2:
It could be meaningful to preserve existing data in an ext4 partition when backing up a setup which used another ext4 partition. And if the ext4 partition is also used for storage apart from the BerryBoot installs, then preservation of such content would be crucial. But for most cases it should be OK to start with formatting the destination partition. (Though always with a warning to the user so he can abort the process before formatting starts.)

**Comment by maxnet** [comment]
New Berryboot version (available through the "add OS" button) has a new version of squashfs-tools that should work better.
Haven't tested it that extensively though.

**Comment by friarbird** [comment]
Maxnet, thank you for attending to this so promptly.
