### ISSUE TITLE
unable to boot ArchARM with berryboot

### ISSUE THREAD

**Issue by RafTim** [maxnet/berryboot#22]
I downloaded the latest ArchARM Iso and followed the instructions given for custom distributions on 
http://www.berryterminal.com/doku.php/berryboot?do=backlink#adding_your_own_custom_operating_systems_to_the_menu

Unfortunately I was not able to boot it because the issue

```
error: having a symlink for /lib and/or /sbin inside your image is not allowed!
This conflicts with the shared AUFS folders
...
switch root: can't execute '/sbin/init': no such file or directory
...
```

appears. Is there a chance that distributions with a symlinked /lib folder could get support? Maybe it is possible, with some alternate installation mode in berryboot, to restart and load the original boot partition from a distribution?

**Comment by maxnet** [comment]
Problem is that we have a number of folders shared between all distributions, like /lib/modules.
The method used for sharing doesn't get along with symlinks.

As a workaround reverse the symlink so that /usr/lib points to /lib like this:

sudo kpartx -av archlinux-hf-2012-09-18.img
sudo mount /dev/mapper/loop0p2 /mnt
cd /mnt
sudo rm lib
sudo mv usr/lib lib
cd usr
sudo ln -s ../lib lib

**Comment by RafTim** [comment]
works, thx for the help. It may crash with some internal installers on arch, which assume that /lib is a symlink, but changing the packagebuild helps here
