### ISSUE TITLE
wifi loaded after iscsi search

### ISSUE THREAD

**Issue by Vikingfr** [maxnet/berryboot#282]
Hi,

i've the bug as this one:
https://github.com/maxnet/berryboot/issues/87

During fresh install, wifi driver is loaded, then iscsi is configured. But after rebbot, wifi doesn't start before iscsi searching.
I'm using PI Zero, D-Link DWA131 (which work fine during install) and BerryBoot from "berryboot-20160209-pi0-pi1.zip".
During install, iscsi was set up, and some distributions were downloaded (so I'm sure wifi dongle is supported)

cmdline.txt:
`smsc95xx.turbo_mode=N elevator=deadline quiet bootmenutimeout=10 datadev=sda1 qmap=fr`

iscsi.sh:

```
/sbin/iscsistart -i "iqn.2012-08.com.berryboot:myPi" -g 1 -t "synology:DiskStation211.Rasp-1" -a "192.168.5.252"
```

wpa_supplicant.conf:

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
ap_scan=1

update_config=1
network={
    ssid="PRIV"
    psk="xxxxxx"
}
```

config.txt:

```
disable_overscan=1
start_x=1
gpu_mem=128
max_usb_current=1

# Enable on-board audio
dtparam=audio=on

# Berryboot settings, do not change
initramfs berryboot.img

kernel=kernel_rpi2_aufs.img

[pi0]
kernel=kernel_rpi_aufs.img

[pi1]
kernel=kernel_rpi_aufs.img

# Warning: CMA does not work properly in newer firmware versions
#
#cma_lwm=16
#cma_hwm=32
#cma_offline_start=16

[all]
```

(sorry if bad english, I'm french)

**Comment by paulator** [comment]
Same here. Works perfect on LAN connection but not with WIFI connection. 

Environment: RPI3, berryboot-20160930-pi2-pi3.zip

**Comment by Ikyrz** [comment]
Hi
do you have resolved your problem please ?

**Comment by lulol** [comment]
Guess not. I'm having this same issue (wired works, wifi keeps `Waiting for network to be ready`) with the latest release available:
`berryboot-20180729-pi0-pi1-pi2-pi3.zip sha1sum: a4659c44826253c1704ef30bd6cf0eb347a02c1e`

Also had to manually change `datadev=sda2` to `datadev=iscsi` in `cmdline.txt` and `uEnv.txt` as others have stated previously because with a clean target partition shared with `tgtd` initially showed the error `Error zero'ing MBR/GPT. SD card may be broken or advertising wrong capacity.` when trying to ext4 format.

Once the berryboot menu has loaded (and so the wifi drivers?) can remove the ethernet wire and install some OS via wifi without much hassle other than the low speed.

**Comment by maxnet** [comment]
>with a clean target partition shared with tgtd initially showed the error Error zero'ing MBR/GPT. SD card 
>may be broken or advertising wrong capacity

The file size of the target does is dividable by 512 ?
E.g. if you want a 4 GB target, make it 4 GiB = 4294967296 bytes, and not 4000000000 bytes.

And wifi is indeed not supported for iSCSI.
You really need a reliable fixed Ethernet connection, as we do not support reconnecting if connection fails either.

**Comment by lulol** [comment]
Indeed it's dividable by 512.

```
$ fdisk -l rpi3.img
Disk rpi3.img: 14.9 GiB, 15938355200 bytes, 31129600 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot  Start      End  Sectors  Size Id Type
rpi3.img1         2048   262143   260096  127M  e W95 FAT16 (LBA)
rpi3.img2       262144 31129599 30867456 14.7G 83 Linux
```
May be the problem is that was a sparse file?
`$ dd if=/dev/zero of=rpi3.img bs=1M count=0 seek=15200`

After testing the NAS via wifi with the RPi3 think that it's just too slow to be usable to mount a network filesystem anyway, and if won't reconnect then is done.

Thank you very much for the clarification. I'll stick to the wired connection.

**Comment by maxnet** [comment]
`ls -l rpi3.img` shows the same size in bytes?

- We obtain the size of the disk device in 512 bytes blocks (by querying /sys/class/block/[device]/size)
- And then zero out the start and end blocks as that is where leftover MBR and GPT partition tables from a previous installation can reside. Using the following commands:

```
dd conv=fsync count=1 bs=8192 if=/dev/zero of=/dev/[disk device]
dd conv=fsync count=8 bs=512 if=/dev/zero seek=[size of disk device in blocks minus 8] of=/dev/[disk device]
```

If either of those return an error code, you get that error message.
The error message says SD card, because the same code is used on SD cards, but it is actually the iSCSI device it is failing on in this case.

**Comment by lulol** [comment]
Yes, the file size that fdisk reports is the same.
```
$ ls -l rpi3.img 
-rw-rw-r-- 1 lulol lulol 15938355200 Aug 14 23:17 rpi3.img
```
In a console opened from the berryboot menu with the rpi3.img file:
```
# cat /sys/class/block/sda/size
31129600
```
And (now once installed) can write without error these first 8192 bytes to `/dev/sda` but the last 4096 bytes from `/dev/iscsi` fail.
```# ls -l /dev/iscsi
lrwxrwxrwx    1 root     root             9 Jan  1 00:00 /dev/iscsi -> /dev/sda2
# dd conv=fsync count=8 bs=512 if=/dev/zero seek=$((31129600-8)) of=/dev/iscsi
dd: /dev/iscsi: Invalid argument
```
That is a bit cryptic out of range error, but accurate.

Have realized that my targets have configured the `block-size` to the disk native 4K sectors instead of 512, and in the running berryboot system fdisk is reporting bogus sizes, but that seems unrelated to this issue.
```
Disk /dev/sda: 14.9 GiB, 15938355200 bytes, 3891200 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot  Start      End  Sectors   Size Id Type
/dev/sda1         2048   262143   260096  1016M  e W95 FAT16 (LBA)
/dev/sda2       262144 31129599 30867456 117.8G 83 Linux
```

Unfortunatelly changing the target sector size to 512 doesn't seem to solve the problem despite fdisk now reporting the correct size within the berryboot environment ([same as above](https://github.com/maxnet/berryboot/issues/282#issuecomment-413004413)).


The key issue seems to be:
<hr>

The last sector is reported by fdisk as 31129599 but we also have the FAT16 partition before so `/dev/iscsi` only has 30867456 sectors because is a symlink to `/dev/sda2` and not to the full disk `/dev/sda` from where the size was obtained (from `/sys/class/block/sda/size` instead of `/sys/class/block/sda2/size`)  hence that is why `dd conv=fsync count=8 bs=512 if=/dev/zero seek=31129592 of=/dev/iscsi` fails, and of course, 
```
# dd conv=fsync count=8 bs=512 if=/dev/zero seek=30867449 of=/dev/iscsi
dd: writting '/dev/iscsi': No space left on device
8+0 records in
7+0 records out
```
seems to confirm it. Shouldn't the GPT zeroing be written to `/dev/sda` instead of `/dev/iscsi` ?

<hr>

By the way, I missed not having `nc` or `script` compiled in with busybox to more easily transfer all command output without having to write them to the sd card.

Many thanks for the detailed insight of the inner workings, made debugging this issue so easy. (If I'm not mistaken, I think) :+1: I would submit a pull request, but without testing it I'll leave it for you. :cake:

**Comment by maxnet** [comment]
>Shouldn't the GPT zeroing be written to /dev/sda instead of /dev/iscsi ?

You do have the latest Berryboot?

As it is supposed to be already doing that.

https://github.com/maxnet/berryboot/blob/berryboot2015/BerrybootGUI2.0/driveformatthread.cpp#L39
https://github.com/maxnet/berryboot/blob/berryboot2015/BerrybootGUI2.0/installer.cpp#L953

If dev == "iscsi" it goes looking for a disk device under /sys/class/block that symlinks to a path that has /session in it (which indicates it belongs to an iscsi session), but it should not have a /partition subfolder, so shouldn't be a partition.
That should result in it using /dev/sda
At least in theory.

**Comment by lulol** [comment]
Didn't compile my own from source.

I'm using the latest release available from the [berryboot web page](https://berryterminal.com/doku.php/berryboot):
`berryboot-20180729-pi0-pi1-pi2-pi3.zip sha1sum: a4659c44826253c1704ef30bd6cf0eb347a02c1e`

**Comment by maxnet** [comment]
Are you sure you didn't accidentally use 20180715 ?
As the FAT partition on iSCSI is also supposed to be removed since 20180729.

**Comment by maxnet** [comment]
Hmm, my code does expect that the iSCSI drive is listed in /sys immediately after making the connection with iscsistart.
Perhaps that isn't always the case and there should be a delay of some sort.

**Comment by lulol** [comment]
I do not have 20180715.

The only recent berryboot file in my downloads is this berryboot-20180729-pi0-pi1-pi2-pi3.zip and the sha1sum matches.

**Comment by lulol** [comment]
I can't assure that your code is actually using `/dev/iscsi` to zero the GPT in my setup, I assumed it was  from your [quoted code above](https://github.com/maxnet/berryboot/issues/282#issuecomment-413013753):

> `dd conv=fsync count=8 bs=512 if=/dev/zero seek=<size of disk device minus 8> of=/dev/<iscsi device>`


May be I didn't understand it correctly, but still the issue is consistently reproducible.

**Comment by maxnet** [comment]
[berryboot-iscsi-delay.zip](https://github.com/maxnet/berryboot/files/2288845/berryboot-iscsi-delay.zip)

Can you try if the following berryboot.img works better? (combine it with the other files)

Has a delay between connecting to iSCSI target, and trying to find out what the iSCSI drive is.
And should print device it tries to zero out if it fails.

**Comment by lulol** [comment]
Yes! The zeroing error is gone and the formatting starts right away. :+1: Good work!

I'll try a few more times just to be sure. ;)

**Comment by lulol** [comment]
3/3 OK.

So seems solved always that the target is mounted fast enough. Now someone should test it with older RPi 0/1.

**Comment by dmshimself** [comment]
I had exactly this issue with a pi zero, but the berryboot image with delay gives a kernel panic, I'm guessing because it is far too old now :-)  Is there any possibility of a similar fix for the current release?  The wifi speed is plenty fast enough on my zero for the OS I'll be using.
