### ISSUE TITLE
Upgrading BerryBoot manually on a computer with the SD card mounted

### ISSUE THREAD

**Issue by tyilo** [maxnet/berryboot#29]
Yesterday, when I tried to boot Raspbian from BerryBoot, I got an error.
I have had this error one time before and upgrading BerryBoot fixed it.

I then selected "Add OS" in the BerryBoot menu and it told me there was an update available. However when installing this update, BerryBoot kept on giving me the error "Error writing to SD".

I then mounted the SD card on my computer and replaced every file on the FAT partition with the newer version from [here](http://downloads.sourceforge.net/project/berryboot/berryboot-20130311.zip). (except `cmdline.txt`)

When I try to boot any OS installed I get the error file not found.

Have I lost all my data from the OS'es?

If so, could you explain how to upgrade BerryBoot from your computer, without this happening?

**Comment by maxnet** [comment]
> BerryBoot kept on giving me the error "Error writing to SD".

Could indicate your SD card is broken or ran out of write cycles (flash storage can only be written to a limited number of times).

> When I try to boot any OS installed I get the error file not found.

Probably also a corrupted file system.
You can try to repair it from within the Berryboot menu editor by pressing ">>" -> "repair file system"

However this causes a lot of writes to the SD card, and in case your SD card is out of write cycles will not work.
In that case it is better take a disk image of the entire SD card first, and write that to a fresh SD card before attempting repair.

Taking a disk image can be done with dd if you have Linux on your desktop, or under Windows with a tool like Win32DiskImager.
In the case of Win32DiskImager:
- enter a filename to save the contents of the SD card to. Make sure the drive you are saving the image to has plenty of space. (e.g. if it is a 8 gb SD card, you need 8 gb of free disk space).
- press the "read" button to read from SD card, and save to disk.
- after it is done, you can "write" the image file again to a fresh blank SD card which must be at least the size of the old one.

**Comment by tyilo** [comment]
Is the OS'es located in the FAT partition?

If so, I have already replaced it with the newer version of BerryBoot and have lost my data.

I don't think there is anything wrong with the SD card, as I was able to replace the files on the FAT partition from my computer, after I got the "Error writing to SD" error.

**Comment by maxnet** [comment]
> Is the OS'es located in the FAT partition?
> If so, I have already replaced it with the newer version of BerryBoot and have lost my data.

No, the operating system data is on the second (ext4) partition.
So replacing anything on the FAT partition should not affect that.
However if there is something wrong with the SD card itself it can affect both partitions.

And if there is an unclean shutdown it can corrupt the file system structures.
However that should be fixable with the "repair file systems" option.

> I don't think there is anything wrong with the SD card, as I was able to replace the files on the FAT partition from 
> my computer, after I got the "Error writing to SD" error.

Not sure if Windows shows all errors though, due to write caching.
When copying files Windows already closes the "copying files" progress bar window before it is actually done writing. It continues to finish writing in the background for some seconds, and any error happening then may or may not be displayed.

**Comment by tyilo** [comment]
I'm not using Windows, I'm using Mac OS X.

After repairing one of my two OS'es installed, they are now both gone from the BerryBoot menu.

**Comment by maxnet** [comment]
> After repairing one of my two OS'es installed, they are now both gone from the BerryBoot menu.

It does a file system check of the entire ext4 data partition, rather than a single OS.
Unfortunately that causes a lot of writes to the SD card, and there is always a chance that it makes the corruption worse.

You may be able to recover individual files by booting an Ubuntu live DVD on your normal computer and accessing the ext4 paritition on the SD card.
Your files are in the /data folder on the second partition.
But consider the SD card as a whole broken beyond repair.

**Comment by tyilo** [comment]
The `/data` directory doesn't exist, only `images`, `lost+found` and `shared`, but thanks for the help.

**Comment by maxnet** [comment]
It may have moved the files that where in /data to /lost+found/some_number if the /data folder was corrupted.
