### ISSUE TITLE
Add RISC OS / Simplify OS addition process

### ISSUE THREAD

**Issue by lsathomas** [maxnet/berryboot#315]
It would be best to have a simplified OS addition process that does not require a special linux setup. Barring that, the ARM RISC OS (archimedes, acorn) https://www.riscosopen.org/ should be an option as it is/was a very popular OS for ARM RISC CPUs.

**Comment by pswiifanwmi** [comment]
Can it be Squashed?  That's what BerryBoot relies on.  As for the addition process, I agree, it is tedious, but that process is necessary as the linux OSes added need to become squash images.  As for RISC, I seriously doubt that it can work with BB as every os it boots runs off of the same kernel by design.  As for RISC, it doesn't run Linux as far as I know.  Correct me if I'm wrong.  I'm no expert on RISC.

**Comment by maxnet** [comment]
No, we can only support operating systems that are able to share an ext4 partition nicely.
And Risc OS does not support partitions, nor understands ext4.
