### ISSUE TITLE
Berry Boot use for embedded systems

### ISSUE THREAD

**Issue by rjungbeck** [maxnet/berryboot#380]
We think about using Berry Boot for installaling and updating embedded systems.

We would need an own https server for the images (that make only sense for our systems). Is there any documentation about the file structure needed there?

Is there a way to configure Berry Boot (ie download server url, files to ignore on backup, os boot configuration files)  via a text file in the image?

**Comment by maxnet** [comment]
>We would need an own https server for the images (that make only sense for our systems). 

https cannot be used for the repo server as https by design requires correct date and time settings, which embedded systems without RTC typically lack.

Can use an S/MIME signed repository file instead.
There is no documentation, but you can learn by example by looking at our file: http://dl.berryboot.com/distro.smime

Create a ``berryboot.ini`` on the FAT partition of the SD card with the URL to your own repo:

```
[repo]
url=http://your-server/file.smime
```

And put your public key file as ``berryboot.crt`` on the FAT partition.

File format for the images is squashfs.
