### ISSUE TITLE
Auto re-try or reboot if fail to load ISCSI LUN

### ISSUE THREAD

**Issue by ben423423n32j14e** [maxnet/berryboot#421]
As the title says, we need an auto re-try or reboot function in Berryboot if an ISCSI LUN fails to mount automatically.

I run a home automation server on Raspberry Pi connected to my Synology NAS, the weak point is if for some reason the LUN does not mount via Berryboot manual intervention is required to try again.

**Comment by maxnet** [comment]
Have added retrying forever to the latest version.
If using Synology do make sure you have the "Allow multiple sessions from one or more iSCSI initiators” box checked in the advanced settings of the target.
Otherwise subsequent tries will also fail if there is already an existing stale session created by a previous boot.
