### ISSUE TITLE
Added file 'ssh' to boot partition, but can't ssh into OS

### ISSUE THREAD

**Issue by mikegilchrist** [maxnet/berryboot#454]
I created the file 'ssh' in my berryboot boot partition.  I downloaded Jessie Lite, installed it, but can't ssh into it.  I mounted the SD on my computer and found the /etc/ssh/sshd_config file, but saw commands for enabling ssh.

**Comment by Nilpo** [comment]
Just enable it manually with `sudo update-rc.d ssh enable`.

**Comment by tam481** [comment]
How do you do that if you can't SSH into the system? I'm trying to make a completely headless setup. I would like to use VNC to select the OS and that OS would have SSH enabled and Wifi set up. Is there a way to achieve this?

**Comment by Nilpo** [comment]
You can do it when you set up the SD card.

**Comment by tam481** [comment]
I'm not sure I understand what you mean.

I formatted the MicroSD as FAT32, copied over the contents of the Berryboot zip file, edited the cmdline.txt file to enable vnc (which works), also created wpa_supplicant and a file called ssh in the same place. Wifi works and I can VNC into the server to install Raspbian Lite. Once I boot into that nothing happens. I can ping the IP address of the node which means that wifi is working but SSH reuses the connection

**Comment by carry0987** [comment]
@tam481 I have the same question, how to enable SSH on raspbian with berryboot if I want to use headless install.

**Comment by maxnet** [comment]
Not supported.
One can do it from the shell, but that is not available through VNC either.

**Comment by carry0987** [comment]
@maxnet  So if I want to do it, I can only edit images in other place to enable SSH?

**Comment by maxnet** [comment]
Yes
We do not target headless users.

**Comment by Nilpo** [comment]
After running BerryBoot the first time, put the microSD card into your PC and add the `ssh` file to the boot partition then. Rasbpian will enable SSH when it boots.

**Comment by carry0987** [comment]
@Nilpo Really?! I will try it , thanks!!

**Comment by maxnet** [comment]
Whether that will work depends on wheter the Raspbian image you have mounts /boot by default.
Not all versions do.
Disabled it earlier because they added scripts stealing Berryboot's wpa_supplicant.conf out of the FAT partition.

Either way, headless operation is not a supported feature.
vncinstall was originally added to be able to take screenshots of Berryboot, without proper HDMI capture equipement.

**Comment by carry0987** [comment]
@maxnet  ok, thanks a lot!!
I'll try to add ssh file to raspbian image by default!

**Comment by mooyxu** [comment]
> @maxnet ok, thanks a lot!!
> I'll try to add ssh file to raspbian image by default!

Hi, have you solved this problem?
I have got the same problem, 
and tried to add ssh into cmdline.txt and empty file called ssh into /root path.
But they didn't work any more...
So, have you solved this?
I don't want to get a display because it is very inconvenient...

**Comment by poudenes** [comment]
Berryboot will be the full master when its possible to have option to add the "touch ssh" in every image you create. fully headless install will be great... Why does it not supported and only see: we do not support headless users... On the site there is a tutorial to do a headless install of Berryboot with VNC... so there is some support, and why not the most critical one "touch ssh"....

**Comment by Nilpo** [comment]
You have have physical access to the SD card when you install BerryBoot. Why not enable SSH then? Or, enable it on first boot. I can't think of a scenario when you would need to automate this. Does anyone have an example?

**Comment by poudenes** [comment]
I have my RPi in the fusebox. So when I want install a different OS then its not handful to get the RPi out of the fusebox and connect it to a HDMI monitor, add keyboard and mouse to it.

When you can put SSH on directly you can access the new OS from SSH without all the handling above. Thats the nice thing of headless config option.

This is my config, a full home automation system. Want add a new RPi with Berryboot for some test things. Then I cant access it physical because it will also connect to a SSD card.

![IMG_1436](https://user-images.githubusercontent.com/4399532/59577548-7c01e700-90c4-11e9-93ee-a5d1eb70292e.JPG)
