### ISSUE TITLE
Rasbperry Pi 3 / 3b+ support status unclear

### ISSUE THREAD

**Issue by rekcodocker** [maxnet/berryboot#694]
This is not a duplicate although it is related.
It is unclear from reading the Berryboot-page if previous raspberries are supported.

The main Berryboot page mentions the Raspberry in general (referring to all models).
But it offers a download only for the Raspberry Pi 4. 
This is a request to update the main berryboot page. Are the previous raspberries supported, or are they not?

**Comment by maxnet** [comment]
I do not provide technical support for older Pi.

Pi 4 image may still work on Pi 3 (as that supports 64-bit as well).
But I did not test it.

**Comment by rekcodocker** [comment]
That's too bad; it works for me on a Pi 3B.  Though but not supporting it is your choice.
It would be better to explicitly mention this on the main page.
Something like

Only PI4 is actively supported. Older models are not supported. Users have reported that the PI4 image works for them on the Pi 3B.

Thanks for the info!

**Comment by HinTak** [comment]
Well, the code is open there... people who want it to work that way can always try to make it happen themselves... (and I think there is a paypal sponsorship link for @maxnet somewhere too... hint hint).

**Comment by maxnet** [comment]
>Well, the code is open there... people who want it to work that way can always try to make it happen themselves... (and I think 
>there is a paypal sponsorship link for @maxnet somewhere too... hint hint).

Eh, no.
I do not accept donations.
(Being a company owner, there is a risk that it would be perceived as taxable income, which is an administrative burden, for money I do not really need).

While there are third parties soliciting money for Berryboot images, that is not me.

**Comment by HinTak** [comment]
Oops, sorry about that! I must have seen the PayPal logo on one of the others (the one hosting distro images?). I do have a donate link (just a plain text url), but the sort of money I get is too pitiful to qualify as income :-).

**Comment by HinTak** [comment]
Argh, I thought I have seen the PayPal logo / image somewhere associated with berryboot - it is this https://berryboot.alexgoldcheidt.com/ (which is also posted in a few other issues). It appears that he just provides adapted distro images, rather than berryboot itself.

Well, I do provide adapted berryboot itself, but I don't use it actually (and therefore don't test anything I "released") . Looking at and building berryboot was/is rather a way for me to get into arm/pi linux driver development, having a mostly x86 linux driver background so far.
