### ISSUE TITLE
iscsi fresh install: cannot find my data partition

### ISSUE THREAD

**Issue by husio-org** [maxnet/berryboot#87]
Hi!

I managed to install Raspbian on an iSCSI target using berryboot. that was impressive.

However, it won't boot with the message : "cannot find my data partition".

I think it is attempting to mount the iSCSI partition before setting up the network.

The network settings was DHCP and I cannot see any request for DHCP during boot.

I wonder if the menu entry has been properly created or not.

anybody having this problem?

**Comment by husio-org** [comment]
looks like the installation did not add the following options to my cmdline.txt file:

ip=dhcp datadev=iscsi 

may be I was supposed to add them in "advanced" menu setup?

other options such as keymap were passed into the cmdline.txt correctly.

so, adding by hand workarounds the problem... but I suppose the installer should do it.

**Comment by maxnet** [comment]
Only needs iscsi in cmdline.txt, not ip=dhcp

We wait for up to 5 seconds for networking to be ready.
If it takes longer to get network connectivity, it will fail.
E.g. this can be the case if you have the Spanning Tree Protocol enabled on the Ethernet switch, but did not enable portfast.

**Comment by maxnet** [comment]
unable to reproduce

**Comment by claco** [comment]
Same for me. Just did a fresh download of the berryboot zip, installed wheezy via Wifi dongle + dhcp connected to iscsi, and on reboot, no sda error. datadev=iscsi was indeed not in my cmdline.txt

Even with the right datadev, iscsi fails because the wifi driver isn't yet loaded, in contrast to it being loaded for the initial setup. During the initial install, the dongle was lit and blinking. During the normal boot after the install, the light never goes on [leading me to believe the driver isn't loading yet].

Plugging in an ethernet cable at this point yields a normal iSCSI boot process.

**Comment by Vikingfr** [comment]
Hi,
same problem for me. Wifi driver load after iscsi.
Duing install, wifi load before setting up iscsi.
I'm using "berryboot-20160209-pi0-pi1" on Pi Zero
