### ISSUE TITLE
Using MCE remote on image selection

### ISSUE THREAD

**Issue by brooc** [maxnet/berryboot#9]
Hi,
I want to use my IR remote for image selection.
The reason is that I have one image that is Openelec and another Raspbian image that I want to select between using the same remote I use for controlling the Openelec image.
I pulled the sources and found that the lirc kernel modules are compiled but no modules are loaded what so ever.

Is there a way to control the boot menu using an IR remote?
Thanks

**Comment by maxnet** [comment]
We do support image selection using your normal TV remote through HDMI CEC.
But not through LIRC. That requires more than just loading the kernel modules (needs userspace LIRC daemon, configuration, etc.)

**Comment by brooc** [comment]
My TV does not support CEC (only new TVs do...)
Could you point me in the direction of what I would need to do in order to enable this?

**Comment by maxnet** [comment]
- modify buildroot-2012.05/kernel-config so that the necessary drivers are build into the kernel instead of module
- create a LIRC buildroot package and enable it in the buildroot configuration. http://www.buildroot.org/downloads/manual/manual.html#adding-packages
- add the commands to start LIRC daemon to buildroot-2012.05/package/berrybootgui2/init
- ./rebuild-berryboot.sh

**Comment by brooc** [comment]
Thanks a lot!
I will try this and will post back my progress.

**Comment by maxnet** [comment]
Closing as issue > 4 months old
